service: laravel

provider:
    name: aws
    region: us-east-1
    stage: dev
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    stackTags:
      ManagerBy: serverless
      Role: "lambda deploy"
      Project: self:service
      Environment: ${opt:stage, self:provider.stage}
    deploymentBucket:
      name: toolkitdeveloper.com

custom:
    stage: ${opt:stage, self:provider.stage}
    prefix: ${self:service}-${self:custom.stage}
    web: ${self:custom.prefix}-web
    artisan: ${self:custom.prefix}-artisan

package:
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'
        - '!docker/**'
        - '!stubs/**'

functions:
    web:
        name: ${self:custom.web}
        handler: public/index.php
        timeout: 28
        layers:
            - ${bref:layer.php-81-fpm}
        events:
            - httpApi: '*'

    artisan:
        name: ${self:custom.artisan}
        handler: artisan
        timeout: 120 # in seconds
        layers:
            - ${bref:layer.php-81}
            - ${bref:layer.console}

plugins:
    - ./vendor/bref/bref
    - serverless-deployment-bucket
